ДЗ 1
ValentinaAsk/2020-1-Atom-QA-Python-V-Askretkova pull request #1
Opened 2020-03-01 17:02 UTC by ValentinaAsk

# Домашнее задание № 1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
написаны тесты для 5 типов данных

2020-03-04 19:30 UTC, sniiick requested changes
Мелкие замечания + нужно удалить файлы .DS_Store из всех папок. можно добавить в .gitignore.

А так все отлично.

2020-03-04 19:30 UTC, snicks92 commented on homework1/test_int.py
> +            assert 0 == (data // (data + 1000))
Мелкое замечание, не хватает пустой строки в конце файла

2020-03-04 19:30 UTC, snicks92 commented on homework1/test_string.py
> +	                              (1, 2),
Тут что то уехало как то странно по отступам

2020-03-04 19:30 UTC, snicks92 commented on homework1/test_string.py
> +                                      '{1} {0}'.format('world', 'hello')])
давай уж сразу f-строки добавим

2020-03-04 19:30 UTC, snicks92 commented on homework1/test_dict.py
> +            assert True
`assert True` или `assert False` в блоке pytest.raises не требуется, так как либо будет рейз и пайтест это прожует, либо рейза не будет и пайтест об этом сообщит. предлагаю везде это убрать.

2020-03-05 07:35 UTC, ValentinaAsk commented
@snicks92 
внесены исправления

2020-03-06 19:43 UTC, sniiick approved these changes

2020-03-06 19:44 UTC, merged