дз 2
ValentinaAsk/2020-1-Atom-QA-Python-V-Askretkova pull request #2
Opened 2020-04-02 18:32 UTC by ValentinaAsk

# Домашнее задание № 2

Прошу @snicks92 или @z1ll1 проверить или @SK1995 его 

Что было сделано:
сделана домашняя работа 2

2020-04-04 12:02 UTC, snicks92 commented
Нужен ребейз на мастер с исправлением конфликта. Нужно удалить коммиты с первой домашкой.

2020-04-12 12:18 UTC, sniiick requested changes
Все хорошо, мелкие замечания в комментах + лишний файлик cm от селеноида, он не нужен

2020-04-12 12:18 UTC, snicks92 commented on homework2/ui/conftest.py
> +def pytest_addoption(parser):
Надо наверное вынести этот метод в рутовый конфтест в homework2/conftest.py, иначе при запуске всех тестов невозможно будет передать опции

2020-04-12 12:18 UTC, snicks92 commented on homework2/api/api/api_client.py
> +        location = 'https://target.my.com/api/v2/remarketing/segments.json?fields=relations__object_type,relations__object_id,relations__params,relations_count,id,name,pass_condition,created,campaign
Слишком длинная строчка. Если мне не изменяет память то параметры `?fields=relations__object_type,relations__object_id,relations__params,relations_count,id,name,pass_condition,created,campaign_ids,users,flags` можно убрать.

2020-04-12 19:04 UTC, ValentinaAsk commented
Прошу @snicks92 проверить изменения

Что было сделано:
удален cm
перенесен conftest
изменены пути импортов
соращен урл

2020-04-15 14:52 UTC, sniiick requested changes
По прошлым замечаниям ок, но в новых коммитах добавился мусор вида homework2/.idea
Давай удалим и приму домашку

2020-04-15 16:07 UTC, ValentinaAsk commented
удалена папка .idea @snicks92

2020-04-15 17:06 UTC, sniiick approved these changes

2020-04-15 17:06 UTC, merged

2020-04-15 17:07 UTC, snicks92 commented
Приято. Балл сниму за conftest и мелькающий мусор, итого 17